export const movieEndpoints = {
  changes: 'movie/changes',
  latest: 'movie/latest',
  nowPlaying: 'movie/now_playing',
  popular: 'movie/popular',
  topRated: 'movie/top_rated',
  upcoming: 'movie/upcoming',
  details: (id: number) => `movie/${id}`,
  accountStates: (id: number) => `movie/${id}/account_states`,
  alternativeTitles: (id: number) => `movie/${id}/alternative_titles`,
  itemChanges: (id: number) => `movie/${id}/changes`,
  credits: (id: number) => `movie/${id}/credits`,
  externalIds: (id: number) => `movie/${id}/external_ids`,
  images: (id: number) => `movie/${id}/images`,
  keywords: (id: number) => `movie/${id}/keywords`,
  lists: (id: number) => `movie/${id}/lists`,
  recommendations: (id: number) => `movie/${id}/recommendations`,
  releaseDates: (id: number) => `movie/${id}/release_dates`,
  reviews: (id: number) => `movie/${id}/reviews`,
  similar: (id: number) => `movie/${id}/similar`,
  translations: (id: number) => `movie/${id}/translations`,
  videos: (id: number) => `movie/${id}/videos`,
  watchProviders: (id: number) => `movie/${id}/watch/providers`,
  trending: (time: 'day' | 'week') => `trending/movie/${time}`,
} as const;
